### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by PROPHESSOR**
Сохранение анонимного ID у юзверя, что бы не миллионилось в глазах

### CODE REVIEW

**Comment by daaru00** [comment]
Hi @PROPHESSOR 

I saw you have changed the default language to Russian:
```javascript
userLanguage: "ru"
```
this is not a good practice, the default global language in IT is English

I noticed also you are changed the default behavior of userId and clientId using a localStorage:
```javascript
clientID: null || localStorage.cid,
userID: null || localStorage.uid,
```
is not a default way, you could use cookies, a system file or generate it using a OS fingerprint.

This changes seems a your own customization, you should not change this file but you can make the same changes using this method after including this file:
```javascript
analytics.userLanguage = "ru";
analytics.clientID = localStorage.cid;
analytics.userID = localStorage.uid;
```

Regards.

**Comment by PROPHESSOR** [comment]
Correctly. About changing the language - I was unable to delete my settings.
About localStorage - I suggested the default working option, because your
method caused interference (instead of 1 the user showed a few).
Therefore, I ask you to take note of this nuance.
PS> Check README: there is an event, not exeption, and a bad example with
e-commerce

2017-08-16 10:15 GMT+03:00 Fabio Gollinucci <notifications@github.com>:

**Comment by PROPHESSOR** [comment]
Correctly. About changing the language - I was unable to delete my settings.
About localStorage - I suggested the default working option, because your method caused interference (instead of 1 the user showed a few).
Therefore, I ask you to take note of this nuance.
PS> Check README: there is an event, not exeption, and a bad example with e-commerce

**Comment by PROPHESSOR** [comment]
P.P.S>I also advise you to use beautifier

**Pull request closed without merging**
